
name: My Super CI
on:
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup PostgreSQL
      uses: Harmon758/postgresql-action@v1.0.0
      with:
        postgresql version: 11
        postgresql db: ${{ secrets.DATASOURCE_DB }}
        postgresql user: ${{ secrets.DATASOURCE_USERNAME }}
        postgresql password: ${{ secrets.DATASOURCE_PASSWORD }}
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
